[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
croc = "F91YBp47Bk8MVGNnPK3edQfrwJLv9eDWRXzfHiVUXk4k"

[programs.devnet]
croc = "F91YBp47Bk8MVGNnPK3edQfrwJLv9eDWRXzfHiVUXk4k"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "user.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
